### ISSUE TITLE
Payment Failure Notifications

### ISSUE THREAD

**Issue by ImPrasadM** [isaumya/razorpay-gravity-forms-updated#1]
Hi @isaumya,
Good Day !!
I just wanted to know can we get Email notifications when Payment gets failure? Because currently I am getting Payment Successful notifications, I need to check Payment Failure test case also so

Thank you

**Comment by isaumya** [comment]
I told you in the earlier message that if a payment gets failed it will remain inside the razorpay popup. Try to use the test API, make a payment and once the payment is done select failure. You will see.

Check out the attached screenshots:
![Imgur](https://i.imgur.com/NGm6mwy.jpg)
![Imgur](https://i.imgur.com/bQsBWoQ.jpg)
![Imgur](https://i.imgur.com/9xO0lVU.jpg)

**Comment by ImPrasadM** [comment]
Okay got it, Currently I am using Test API, I want purchase Live API,  what will be the condition for Live API ? If user entered wrong Card number or Wrong UPI , what will be the condition ? By default Live API is having any option or we have to do that ?

Thank you

**Comment by isaumya** [comment]
@ImPrasadM I've added some screenshots above check. You can get your Live API from your RazorPay dashboard. I'm using the Live APIs on my projects and working fine.

**Comment by ImPrasadM** [comment]
Okay thank you so much.

**Comment by isaumya** [comment]
@ImPrasadM No problem. I'm closing this issue now as I think all of your questions have been answered.
