### ISSUE TITLE
Gravity Forms SMS Notifications

### ISSUE THREAD

**Issue by ImPrasadM** [isaumya/razorpay-gravity-forms-updated#2]
Hi,

I am using this plugin, can you tell me how can I get SMS notification ? Is there any extra plugin I need to add ? Can you please suggest me ? I am getting Email notification, I need to get SMS notification?  Can you please help me ?

Thank you
Prasad Mayya
7760667689

**Comment by isaumya** [comment]
@ImPrasadM I'm not sure about that, but definitely you need a separate Gravity Forms plugin to send SMS notification as by default Gravity Forms send email notification only.
