### ISSUE TITLE
Gravity forms

### ISSUE THREAD

**Issue by ImPrasadM** [isaumya/razorpay-gravity-forms-updated#4]
Hello,

Can you please give solution, I am using conditional logic for product drop down, once we select option that is showing products in other dropdown with price list, like this there is other six products is there, Can I get a solution for how to fetch a different single common product variable name that should easily accessible in my email notification ? In Email notification I need to mention the variable name that should show the product name in my email.

In below image **Choose package** in first drop down, Services are Product drop down, I have applied conditional logic for first drop down

![Gravity-form](https://user-images.githubusercontent.com/25503117/60944106-869b4f00-a305-11e9-84ca-f2997acbc8bc.png)

Can you give a solution for this ?

Thank you

**Comment by isaumya** [comment]
@ImPrasadM first of all, this is a question outside the scope of this plugin and this is basically asking for Gravity Form support, which I'm not providing here. If you need support with Gravity Forms, contact Gravity Forms support or check StackOverflow or watch some YouTube video about how Gravity Forms product section works. I'm sorry but this is not a free support hub for everything Gravity Forms. If you are facing any issues with the plugin, feel free to report that and I would love to look into it, but I can't provide free support to your Gravity Forms issues. Go to Gravity Forms support for that.
