### ISSUE TITLE
Is there a way to make sure the gravity form entry is not submitted in case of payment failure? Right now I see that entry is submitted regardless of whether payment is successful or not

### ISSUE THREAD

**Issue by NithinMathew9415** [isaumya/razorpay-gravity-forms-updated#5]

**Comment by isaumya** [comment]
No. Gravity form will have the entry regardless of whether the payment is successful or not. As gravity forms first create the entry then updated payment status and if the payment is successful the email notification will be sent.

That's the gravity form flow.
